name = "nexus-dapp"
compatibility_date = "2024-01-01"

[build]
command = "npm install --legacy-peer-deps && cd apps/web && npm install --legacy-peer-deps && npm run build"
cwd = "apps/web"

[pages]
build_output_dir = "out"
